# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: "Python Lint & Test"

on:
  push:
    branches: [ v2 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install -d
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --exclude tests --statistics
    - name: Test with pytest
      env:
        FLASK_SKIP_DOTENV: 1
        FLASK_APP: coopcontrol
        FLASK_ENV: test
        COOPCONTROL_ENV: test
      run: |
        pipenv run python -m pytest

